Pin charset-normalizer to a version that supports Python 3.5 on Xenial
ros-infrastructure/ros_buildfarm pull request #905
Opened 2021-09-15 14:32 UTC by nuclearsandwich

As of last night, reconfigure and trigger jobs are failing with the following stacktrace:

```
00:01:20.298 Traceback (most recent call last):
00:01:20.298   File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/api.py", line 5, in <module>
00:01:20.298     from os import PathLike
00:01:20.298 ImportError: cannot import name 'PathLike'
```

This is likely due to the fact that os.PathLike was added in Python 3.6. [charset-normalizer](https://pypi.org/project/charset-normalizer/) updated from 2.0.4 to 2.0.5 on September 14 according to the [release history](https://pypi.org/project/charset-normalizer/#history) and this release likely includes the use of PathLike.

#878 is in progress to move all of our maintenance jobs to Focal but I have not yet run and tested these jobs under Focal so this PR is a possible hotfix to restore builds while we continue the work to run the jobs on Focal.

2021-09-15 20:59 UTC, Ousret commented
Hi,

chardet-normalizer did not drop python 3.5. 
what you are referring to is well tested. 

Did I missed something ? Look at the line specified in your traceback, this should not happen. This portion of code was not changed. 

Regards,

2021-09-15 21:09 UTC, cottsay commented
That's not the full stack trace - here it is, which shows that the issue occurs in the handler:
```python
>>> import charset_normalizer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/api.py", line 5, in <module>
    from os import PathLike
ImportError: cannot import name 'PathLike'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/__init__.py", line 21, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/api.py", line 9, in <module>
    PathLike = Union[str, "os.PathLike[str]"]  # type: ignore
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'PathLike'
```

2021-09-15 21:11 UTC, cottsay commented
The call to `import os` that was added in Ousret/charset_normalizer#81 caused the regression.

2021-09-15 21:20 UTC, Ousret commented
That is puzzling. I did not see that coming. So the typing module ran an eval on this.
With Python 3.5.10 it did not occurs. cf. https://github.com/Ousret/charset_normalizer/pull/98/checks?check_run_id=3602431833

What is the exact version you are using?

2021-09-15 21:27 UTC, cottsay commented
Here's a docker-based repro:
```dockerfile
FROM ubuntu:xenial
RUN apt-get -qq update -y && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y python3-pip
RUN python3 -m pip install charset_normalizer
RUN python3 --version
RUN python3 -c "import charset_normalizer; print('OK')"
```

Results:

<details>

```
$ docker build .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM ubuntu:xenial
 ---> b6f507652425
Step 2/5 : RUN apt-get -qq update -y && DEBIAN_FRONTEND=noninteractive apt-get -qq install -y python3-pip
 ---> Running in 3e73374e1d58
Removing intermediate container 3e73374e1d58
 ---> 4047e6c725ce
Step 3/5 : RUN python3 -m pip install charset_normalizer
 ---> Running in b0a59966d1a9
Collecting charset_normalizer
  Downloading https://files.pythonhosted.org/packages/48/84/aa70b1e0d9d5a76d3d8a4c3d495f8f0524831571f65efe51bb8db8df0eed/charset_normalizer-2.0.5-py3-none-any.whl
Installing collected packages: charset-normalizer
Successfully installed charset-normalizer-2.0.5
You are using pip version 8.1.1, however version 21.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container b0a59966d1a9
 ---> 76b70d06cb3b
Step 4/5 : RUN python3 --version
 ---> Running in c32a28ec24f8
Python 3.5.2
Removing intermediate container c32a28ec24f8
 ---> b490fcbb0d0e
Step 5/5 : RUN python3 -c "import charset_normalizer; print('OK')"
 ---> Running in 553eac2bfee3
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/api.py", line 5, in <module>
    from os import PathLike
ImportError: cannot import name 'PathLike'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/__init__.py", line 21, in <module>
    from .api import from_bytes, from_fp, from_path, normalize
  File "/usr/local/lib/python3.5/dist-packages/charset_normalizer/api.py", line 9, in <module>
    PathLike = Union[str, "os.PathLike[str]"]  # type: ignore
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
AttributeError: module 'os' has no attribute 'PathLike'
The command '/bin/sh -c python3 -c "import charset_normalizer; print('OK')"' returned a non-zero code: 1
```

</details>

2021-09-15 21:33 UTC, Ousret commented
Thanks for the detailed report! I will address as soon as possible this.
I could not see it coming since that behaviour was changed in between Python minors.

2021-09-15 21:34 UTC, cottsay commented
> I could not see it coming since that behaviour was changed in between Python minors.

No worries, I agree that it is very unexpected. Thanks for taking a look.

Out of curiosity, how did you find out about this ticket so quickly? Did GitHub notify you for some reason?

2021-09-15 21:39 UTC, Ousret commented
> Out of curiosity, how did you find out about this ticket so quickly? Did GitHub notify you for some reason?

I take a look, time to time, after each release to identify possible issue. I wish GH had some way to identify those cases.

2021-09-15 21:59 UTC, Ousret commented
Fix merged.

2021-09-15 22:26 UTC, nuclearsandwich commented
> I take a look, time to time, after each release to identify possible issue (using GH search engine). I wish GH had some way to identify those cases.

That's a lot of effort on your part. Thank you very much for looking out for us. Our hope is actually to move forward and pick up the Python version in Focal but we can run a few ad-hoc jobs to test that your patch release addresses the problem in 3.5.2.

2021-09-15 22:33 UTC, Ousret commented
You are welcome.

> that your patch release addresses the problem in 3.5.2

If you could confirm that its fixed, it would be appreciated.

Regards,

2021-09-16 02:17 UTC, cottsay requested changes
@Ousret - I can confirm the fix is working as expected. Thank you. It looks like Python 2 is affected as well.

@nuclearsandwich - I left some suggestions here, some of which are optional and some are critical and are not getting caught by CI. I opened #908 to address the gap in CI, but it will fail to build until we fix this issue (which is good news, really).

Failing build: https://github.com/ros-infrastructure/ros_buildfarm/pull/908/checks?check_run_id=3616777088
With fix: https://github.com/ros-infrastructure/ros_buildfarm/pull/907/checks?check_run_id=3616689383

2021-09-16 20:00 UTC, nuclearsandwich commented
With the move to Focal containers for the affected jobs, this change is no longer needed. It is also likely that a future charset-normalizer release will fix the regression for others running earlier checkouts of ros_buildfarm.

Thanks @cottsay for the review and @Ousret for the pro-active maintenance :love_letter:.

2021-09-16 20:00 UTC, closed without merging